/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardTaskTaskIdRouteImport } from './routes/dashboard/task.$taskId'
import { Route as DashboardProjectProjectIdRouteRouteImport } from './routes/dashboard/project.$projectId/route'
import { Route as DashboardProjectProjectIdIndexRouteImport } from './routes/dashboard/project.$projectId/index'
import { Route as DashboardProjectProjectIdTaskTaskIdRouteImport } from './routes/dashboard/project.$projectId/task.$taskId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTaskTaskIdRoute = DashboardTaskTaskIdRouteImport.update({
  id: '/task/$taskId',
  path: '/task/$taskId',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProjectProjectIdRouteRoute =
  DashboardProjectProjectIdRouteRouteImport.update({
    id: '/project/$projectId',
    path: '/project/$projectId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardProjectProjectIdIndexRoute =
  DashboardProjectProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardProjectProjectIdRouteRoute,
  } as any)
const DashboardProjectProjectIdTaskTaskIdRoute =
  DashboardProjectProjectIdTaskTaskIdRouteImport.update({
    id: '/task/$taskId',
    path: '/task/$taskId',
    getParentRoute: () => DashboardProjectProjectIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/project/$projectId': typeof DashboardProjectProjectIdRouteRouteWithChildren
  '/dashboard/task/$taskId': typeof DashboardTaskTaskIdRoute
  '/dashboard/project/$projectId/': typeof DashboardProjectProjectIdIndexRoute
  '/dashboard/project/$projectId/task/$taskId': typeof DashboardProjectProjectIdTaskTaskIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/task/$taskId': typeof DashboardTaskTaskIdRoute
  '/dashboard/project/$projectId': typeof DashboardProjectProjectIdIndexRoute
  '/dashboard/project/$projectId/task/$taskId': typeof DashboardProjectProjectIdTaskTaskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/project/$projectId': typeof DashboardProjectProjectIdRouteRouteWithChildren
  '/dashboard/task/$taskId': typeof DashboardTaskTaskIdRoute
  '/dashboard/project/$projectId/': typeof DashboardProjectProjectIdIndexRoute
  '/dashboard/project/$projectId/task/$taskId': typeof DashboardProjectProjectIdTaskTaskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/dashboard/'
    | '/dashboard/project/$projectId'
    | '/dashboard/task/$taskId'
    | '/dashboard/project/$projectId/'
    | '/dashboard/project/$projectId/task/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/dashboard/task/$taskId'
    | '/dashboard/project/$projectId'
    | '/dashboard/project/$projectId/task/$taskId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/dashboard/'
    | '/dashboard/project/$projectId'
    | '/dashboard/task/$taskId'
    | '/dashboard/project/$projectId/'
    | '/dashboard/project/$projectId/task/$taskId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/task/$taskId': {
      id: '/dashboard/task/$taskId'
      path: '/task/$taskId'
      fullPath: '/dashboard/task/$taskId'
      preLoaderRoute: typeof DashboardTaskTaskIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/project/$projectId': {
      id: '/dashboard/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/dashboard/project/$projectId'
      preLoaderRoute: typeof DashboardProjectProjectIdRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/project/$projectId/': {
      id: '/dashboard/project/$projectId/'
      path: '/'
      fullPath: '/dashboard/project/$projectId/'
      preLoaderRoute: typeof DashboardProjectProjectIdIndexRouteImport
      parentRoute: typeof DashboardProjectProjectIdRouteRoute
    }
    '/dashboard/project/$projectId/task/$taskId': {
      id: '/dashboard/project/$projectId/task/$taskId'
      path: '/task/$taskId'
      fullPath: '/dashboard/project/$projectId/task/$taskId'
      preLoaderRoute: typeof DashboardProjectProjectIdTaskTaskIdRouteImport
      parentRoute: typeof DashboardProjectProjectIdRouteRoute
    }
  }
}

interface DashboardProjectProjectIdRouteRouteChildren {
  DashboardProjectProjectIdIndexRoute: typeof DashboardProjectProjectIdIndexRoute
  DashboardProjectProjectIdTaskTaskIdRoute: typeof DashboardProjectProjectIdTaskTaskIdRoute
}

const DashboardProjectProjectIdRouteRouteChildren: DashboardProjectProjectIdRouteRouteChildren =
  {
    DashboardProjectProjectIdIndexRoute: DashboardProjectProjectIdIndexRoute,
    DashboardProjectProjectIdTaskTaskIdRoute:
      DashboardProjectProjectIdTaskTaskIdRoute,
  }

const DashboardProjectProjectIdRouteRouteWithChildren =
  DashboardProjectProjectIdRouteRoute._addFileChildren(
    DashboardProjectProjectIdRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardProjectProjectIdRouteRoute: typeof DashboardProjectProjectIdRouteRouteWithChildren
  DashboardTaskTaskIdRoute: typeof DashboardTaskTaskIdRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardProjectProjectIdRouteRoute:
    DashboardProjectProjectIdRouteRouteWithChildren,
  DashboardTaskTaskIdRoute: DashboardTaskTaskIdRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
